name: CI Pipeline

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login Docker
      env:
        DOCKER_USERNAME: ${{ secret.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secret.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t ppxnttt/react-pipeline .
    - name: Push Docker
      run: docker push ppxnttt/react-pipeline:latest
